// Generated by typings
// Source: node_modules/@cycle/rxjs-adapter/lib/index.d.ts
declare module '~@cycle/rxjs-adapter/lib/index' {
import { StreamAdapter } from '@cycle/base';
const RxJSAdapter: StreamAdapter;
export default RxJSAdapter;
}
declare module '@cycle/rxjs-adapter/lib/index' {
export { default } from '~@cycle/rxjs-adapter/lib/index';
}
declare module '@cycle/rxjs-adapter' {
export { default } from '~@cycle/rxjs-adapter/lib/index';
}
